### ISSUE TITLE
Formatar o texto do quem somos

### ISSUE THREAD

**Issue by hiurequeiroz** [portalsemporteiras/portalsemporteiras.github.io#14]
O texto que segue ao lado do video precisa encaixar com o tamanho do video e a cor precisa estar mais elegante e tem que ser responsivo

**Comment by tdruiva** [comment]
![ArchLabs_2020-05-26-14_1366x768](https://user-images.githubusercontent.com/1254745/82943392-ea575680-9f6f-11ea-917f-c80cc4a12d0d.png)

**Comment by Lubagope** [comment]
também acho que ele pode ser com letra em cor clara e fundo da mesma cor que o fundo da sessão quem somos

**Comment by hiurequeiroz** [comment]
eu sou péssimo com essas coisas de cor, mas eu tentei aqui e cheguei nesse resultado, o que vc acha?
![Captura de tela de 2020-05-27 13-52-39](https://user-images.githubusercontent.com/6631731/83049359-6e1d4b80-a021-11ea-8a0a-67b12932ce32.png)

**Comment by hiurequeiroz** [comment]
ou opção dois que a Marcela preferiu
![Captura de tela de 2020-05-27 14-12-15](https://user-images.githubusercontent.com/6631731/83051268-264bf380-a024-11ea-8f63-c9bb7506b8a4.png)

**Comment by portalsemporteiras** [comment]
bom vou fechar.. se algué, se incomodar com o jeito que ficou abrimos de novo
