### ISSUE TITLE
Alterar tamanho dos textos clicáveis do saiba mais

### ISSUE THREAD

**Issue by Lubagope** [portalsemporteiras/portalsemporteiras.github.io#21]
Maiores 
![canvas (10)](https://user-images.githubusercontent.com/50779655/83011010-8ffdda80-9fef-11ea-9c67-c0863b52b2a1.png)

**Comment by hiurequeiroz** [comment]
Veja se ficou bom isso
![Captura de tela de 2020-05-27 10-53-28](https://user-images.githubusercontent.com/6631731/83028991-859c0a80-a008-11ea-9191-cd485c25abba.png)

**Comment by Lubagope** [comment]
otimo!
pq os primeiros dois textos tem fonte de outra cor?

**Comment by hiurequeiroz** [comment]
ah isso fica assim qndo vc já clicou no link e o browser guardou o cache

**Comment by hiurequeiroz** [comment]
@tdruiva como eu relaciono o commit da alteração com essa issue? da para fazer isso mesmo depois de já ter feito o commit?
