### ISSUE TITLE
A pagina "estatuto"  sumiu

### ISSUE THREAD

**Issue by hiurequeiroz** [portalsemporteiras/portalsemporteiras.github.io#23]
ao adicionar a pagina "como fazer parte" #22  a pagina "estatuto" sumiu

**Comment by tdruiva** [comment]
Falta adicionar um `-` antes do [`nome`](https://github.com/portalsemporteiras/portalsemporteiras.github.io/commit/de6be46a6624676b6b77004bd11d44d7f116283c#diff-44eb625004a8966c1320b406cd61027eR19).

**Comment by tdruiva** [comment]
Resolvido na #24

**Comment by hiurequeiroz** [comment]
massa, valeu TItania
