### ISSUE TITLE
Pagina inicial do #novolayout

### ISSUE THREAD

**Issue by portalsemporteiras** [portalsemporteiras/portalsemporteiras.github.io#4]
A pagina inicial do  deve conter 3 blocos, a primeira com o logo e um texto a segunda seria "quem somos"  e a terceira "saiba mais" 
@tdruiva

**Comment by tdruiva** [comment]
![photo5069192180135995537](https://user-images.githubusercontent.com/1254745/82759443-e4247700-9dc3-11ea-8d4f-069aadc8f764.jpg)

**Comment by tdruiva** [comment]
No caso da seção "Saiba Mais", a newsletter é a do Nós por Nós? Pq se sim, não seria melhor que isso estivesse dentro da pagina do Nós por Nós?
Com relação ao "Expansão da rede", querem dar destaque pra isso? Pergunto porque isso poderia estar dentro da pagina sobre a "Rede local"

**Comment by portalsemporteiras** [comment]
não essa newslatter é a que a vivi fez para todas as atividades da psp durante o ano passado
na verdade expansão da rede eu mudei para infraestrutura, que seria explicando como fuciona a nossa infra
Já rede local eu pensei em dar uma explicada nisso e um link para quem estiver na psp ser redirecionado

**Comment by portalsemporteiras** [comment]
eu não to conseguindo assignar pra vc essa issue, pq será? eu consigo assignar até para a Lu que nem ta como membro, mas para vc não vai

**Comment by tdruiva** [comment]
blz, newsletter eh outra coisa...

> na verdade expansão da rede eu mudei para infraestrutura

ok, onde vc mudou? eu preciso fazer algo? acho que não pq a issue já foi fechada

sobre assignar, não sei pq nao ta rolando...
